project:
  type: website
  output-dir: "docs"
  resources:
    - dados/**

website:
  favicon: assets/imgs/favicon.jpg
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: assets/imgs/logo.png
    left:
      - href: index.qmd
        text: Início
      - text: "|"
      - href: banco.qmd
        text: Banco De Dados
      - text: "|"
      - href: about.qmd
        text: Sobre
      - text: "|"
      - href: contato.qmd
        text: Contato
    right:
      - icon: github
        href: https://github.com/LEER-IPEN/projeto-banco-de-dados-tintas
  page-footer:
    center: 
      "Copyright © 2026 Todos os direitos reservados por LEER - IPEN <br><br>  Projeto Banco de Dados de Tintas Artísticas - Desenvolvido para pesquisa, ensino e conservação do patrimônio artístico."

filters:
  - carousel

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true


