project:
  type: website
  output-dir: "docs"

website:
  favicon: assets/imgs/favicon.jpg
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: assets/imgs/logo.png
    left:
      - href: banco.qmd
        text: Banco De Dados
      - href: about.qmd
        text: Sobre
      - href: contato.qmd
        text: Contato
    right:
      - icon: github
        href: https://github.com/LEER-IPEN/projeto-banco-de-dados-tintas
  page-footer:
    center: 
      "Copyright Â© 2026 Todos os direitos reservados por LEER - IPEN"

filters:
  - carousel

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true


